export type AirportSeoProfile = {
  code: string;
  city: string;
  country: string;
  airportName: string;
  slug: string;
  domain: string;
  terminalSummary: string;
  trafficSummary: string;
  delayFactors: string[];
  popularSearches: string[];
  routeFocus: string[];
};

export const airportSeoProfiles: AirportSeoProfile[] = [
  {
    code: "DEL",
    city: "Delhi",
    country: "India",
    airportName: "Indira Gandhi International Airport",
    slug: "del",
    domain: "newdelhiairport.in",
    terminalSummary:
      "Delhi Airport is one of India's busiest international gateways, with domestic and international operations across large terminal facilities serving North India, NCR business travel, and long-haul connections.",
    trafficSummary:
      "The airport is a major hub for Indian domestic routes and a strong origin point for flights to the Middle East, Southeast Asia, Europe, and North America.",
    delayFactors: ["winter fog and low visibility", "peak evening departures", "air traffic flow into North India"],
    popularSearches: ["Delhi airport arrivals", "Delhi airport departures today", "DEL airport live status", "Delhi airport delays"],
    routeFocus: ["Mumbai", "Bangalore", "Dubai", "London", "Singapore"],
  },
  {
    code: "BOM",
    city: "Mumbai",
    country: "India",
    airportName: "Chhatrapati Shivaji Maharaj International Airport",
    slug: "bom",
    domain: "csmia.adaniairports.com",
    terminalSummary:
      "Mumbai Airport serves India's financial capital with dense domestic schedules, international long-haul service, and heavy business travel demand.",
    trafficSummary:
      "Mumbai is a key connection point for western India, with frequent flights to Delhi, Bangalore, Goa, Dubai, London, and major Indian metros.",
    delayFactors: ["monsoon weather", "single-airport congestion", "late-night international arrival banks"],
    popularSearches: ["Mumbai airport arrivals", "Mumbai departure today", "BOM airport live status", "Mumbai airport delays"],
    routeFocus: ["Delhi", "Bangalore", "Goa", "Dubai", "London"],
  },
  {
    code: "BLR",
    city: "Bangalore",
    country: "India",
    airportName: "Kempegowda International Airport Bengaluru",
    slug: "blr",
    domain: "bengaluruairport.com",
    terminalSummary:
      "Bangalore Airport supports India's technology capital with domestic business traffic, international departures, and expanding terminal capacity.",
    trafficSummary:
      "The airport is a strong southern India hub, especially for routes to Delhi, Mumbai, Hyderabad, Singapore, Dubai, and European connections.",
    delayFactors: ["evening thunderstorm activity", "surface traffic around airport access roads", "peak business travel waves"],
    popularSearches: ["Bangalore airport arrivals", "Bangalore airport departures", "BLR airport live status", "Bangalore airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Hyderabad", "Singapore", "Dubai"],
  },
  {
    code: "HYD",
    city: "Hyderabad",
    country: "India",
    airportName: "Rajiv Gandhi International Airport",
    slug: "hyd",
    domain: "hyderabad.aero",
    terminalSummary:
      "Hyderabad Airport is a major central-southern India airport serving domestic routes, Gulf connections, technology travel, and cargo-linked aviation demand.",
    trafficSummary:
      "Hyderabad has frequent service to Indian metros and international links to the Middle East, Southeast Asia, and selected long-haul markets.",
    delayFactors: ["late evening connection banks", "seasonal storms", "airport slot and turnaround pressure"],
    popularSearches: ["Hyderabad airport arrivals", "Hyderabad airport departures today", "HYD live flight status", "Hyderabad airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Dubai", "Doha"],
  },
  {
    code: "MAA",
    city: "Chennai",
    country: "India",
    airportName: "Chennai International Airport",
    slug: "maa",
    domain: "aai.aero",
    terminalSummary:
      "Chennai Airport is a major gateway for Tamil Nadu, South India business routes, Southeast Asia services, and Gulf-bound travel.",
    trafficSummary:
      "Chennai handles strong domestic demand and international routes to Singapore, Kuala Lumpur, Dubai, Doha, and other regional hubs.",
    delayFactors: ["coastal weather", "monsoon disruption", "international departure bank congestion"],
    popularSearches: ["Chennai airport arrivals", "Chennai airport departures", "MAA airport live status", "Chennai airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Singapore", "Dubai", "Kuala Lumpur"],
  },
  {
    code: "DXB",
    city: "Dubai",
    country: "United Arab Emirates",
    airportName: "Dubai International Airport",
    slug: "dxb",
    domain: "dubaiairports.ae",
    terminalSummary:
      "Dubai International is one of the world's most important long-haul hubs, connecting Europe, Asia, Africa, the Middle East, Australia, and the Americas.",
    trafficSummary:
      "DXB is built around major international connection banks, high-frequency Emirates operations, and dense regional airline activity.",
    delayFactors: ["large connection waves", "regional weather and visibility", "high runway utilization"],
    popularSearches: ["Dubai airport arrivals", "Dubai airport departures today", "DXB airport live status", "Dubai airport delays"],
    routeFocus: ["Delhi", "London", "Singapore", "Bangkok", "New York"],
  },
  {
    code: "SIN",
    city: "Singapore",
    country: "Singapore",
    airportName: "Singapore Changi Airport",
    slug: "sin",
    domain: "changiairport.com",
    terminalSummary:
      "Singapore Changi is a premier Southeast Asia hub with extensive international connections, efficient terminals, and strong long-haul airline networks.",
    trafficSummary:
      "Changi links Southeast Asia with India, China, Australia, Europe, the Middle East, and North America through frequent regional and long-haul services.",
    delayFactors: ["regional thunderstorm cells", "connection bank pressure", "airspace flow around Southeast Asia"],
    popularSearches: ["Singapore airport arrivals", "Changi departures today", "SIN airport live status", "Singapore airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangkok", "London", "Sydney"],
  },
  {
    code: "BKK",
    city: "Bangkok",
    country: "Thailand",
    airportName: "Suvarnabhumi Airport",
    slug: "bkk",
    domain: "suvarnabhumi.airportthai.co.th",
    terminalSummary:
      "Bangkok Suvarnabhumi is Thailand's main international airport and a major Southeast Asia gateway for leisure, business, and regional transfer traffic.",
    trafficSummary:
      "BKK connects Thailand with India, East Asia, the Middle East, Europe, and domestic Thai destinations through dense regional schedules.",
    delayFactors: ["monsoon storms", "tourism peak periods", "regional arrival and departure waves"],
    popularSearches: ["Bangkok airport arrivals", "Bangkok departures today", "BKK airport live status", "Bangkok airport delays"],
    routeFocus: ["Singapore", "Delhi", "Dubai", "London", "Phuket"],
  },
  {
    code: "LHR",
    city: "London",
    country: "United Kingdom",
    airportName: "London Heathrow Airport",
    slug: "lhr",
    domain: "heathrow.com",
    terminalSummary:
      "London Heathrow is the United Kingdom's largest international airport and one of Europe's most important long-haul connection points.",
    trafficSummary:
      "Heathrow has heavy transatlantic demand, European feeder traffic, India links, Middle East connections, and global premium travel flows.",
    delayFactors: ["European air traffic restrictions", "weather and wind patterns", "slot-controlled runway operations"],
    popularSearches: ["London Heathrow arrivals", "London Heathrow departures today", "LHR airport live status", "Heathrow airport delays"],
    routeFocus: ["New York", "Delhi", "Dubai", "Singapore", "Mumbai"],
  },
  {
    code: "JFK",
    city: "New York",
    country: "United States",
    airportName: "John F. Kennedy International Airport",
    slug: "jfk",
    domain: "jfkairport.com",
    terminalSummary:
      "New York JFK is a major international gateway for the United States, with strong transatlantic, transcontinental, Caribbean, and long-haul service.",
    trafficSummary:
      "JFK serves high-volume international arrivals and departures, premium long-haul routes, and important domestic feeder connections.",
    delayFactors: ["New York airspace congestion", "winter weather", "terminal and runway flow restrictions"],
    popularSearches: ["JFK airport arrivals", "JFK departures today", "New York airport live status", "JFK airport delays"],
    routeFocus: ["London", "Dubai", "Delhi", "Los Angeles", "Paris"],
  },
  {
    code: "LAX",
    city: "Los Angeles",
    country: "United States",
    airportName: "Los Angeles International Airport",
    slug: "lax",
    domain: "flylax.com",
    terminalSummary: "Los Angeles International Airport is a major US West Coast gateway with domestic, transpacific, Latin America, and long-haul international service.",
    trafficSummary: "LAX handles heavy entertainment, business, leisure, and connecting demand across North America, Asia, Australia, Europe, and Latin America.",
    delayFactors: ["coastal weather", "Los Angeles basin congestion", "international arrival banks"],
    popularSearches: ["LAX airport arrivals", "LAX departures today", "Los Angeles airport live status", "LAX airport delays"],
    routeFocus: ["New York", "London", "Tokyo", "Sydney", "Mexico City"],
  },
  {
    code: "ORD",
    city: "Chicago",
    country: "United States",
    airportName: "Chicago O'Hare International Airport",
    slug: "ord",
    domain: "flychicago.com",
    terminalSummary: "Chicago O'Hare is one of the busiest hub airports in North America, supporting dense domestic networks and long-haul international service.",
    trafficSummary: "ORD is a major connecting hub for US domestic flights, transatlantic routes, Latin America service, and Asia links.",
    delayFactors: ["winter weather", "thunderstorms", "hub bank congestion"],
    popularSearches: ["Chicago O'Hare arrivals", "ORD departures today", "ORD airport live status", "Chicago airport delays"],
    routeFocus: ["New York", "Los Angeles", "London", "Toronto", "Tokyo"],
  },
  {
    code: "ATL",
    city: "Atlanta",
    country: "United States",
    airportName: "Hartsfield-Jackson Atlanta International Airport",
    slug: "atl",
    domain: "atl.com",
    terminalSummary: "Atlanta Airport is a massive US hub with high-frequency domestic banks and international routes across the Americas, Europe, Africa, and beyond.",
    trafficSummary: "ATL is built for large-scale connections, making live arrivals, departures, and delay awareness especially useful.",
    delayFactors: ["summer thunderstorms", "connection bank pressure", "high runway utilization"],
    popularSearches: ["Atlanta airport arrivals", "ATL departures today", "ATL airport live status", "Atlanta airport delays"],
    routeFocus: ["New York", "Orlando", "London", "Paris", "Los Angeles"],
  },
  {
    code: "CDG",
    city: "Paris",
    country: "France",
    airportName: "Paris Charles de Gaulle Airport",
    slug: "cdg",
    domain: "parisaeroport.fr",
    terminalSummary: "Paris Charles de Gaulle is France's largest international airport and a major European long-haul and Schengen connection hub.",
    trafficSummary: "CDG connects Europe with North America, Africa, the Middle East, India, and Asia through large airline alliance networks.",
    delayFactors: ["European airspace flow", "weather", "terminal connection waves"],
    popularSearches: ["Paris CDG arrivals", "CDG departures today", "CDG airport live status", "Paris airport delays"],
    routeFocus: ["London", "New York", "Dubai", "Delhi", "Tokyo"],
  },
  {
    code: "FRA",
    city: "Frankfurt",
    country: "Germany",
    airportName: "Frankfurt Airport",
    slug: "fra",
    domain: "frankfurt-airport.com",
    terminalSummary: "Frankfurt Airport is Germany's busiest aviation hub, known for long-haul connectivity, European feeder flights, and cargo operations.",
    trafficSummary: "FRA supports major connections across Europe, North America, India, the Middle East, East Asia, and Africa.",
    delayFactors: ["weather", "European air traffic restrictions", "large connection banks"],
    popularSearches: ["Frankfurt airport arrivals", "FRA departures today", "FRA airport live status", "Frankfurt airport delays"],
    routeFocus: ["London", "Delhi", "New York", "Singapore", "Dubai"],
  },
  {
    code: "DOH",
    city: "Doha",
    country: "Qatar",
    airportName: "Hamad International Airport",
    slug: "doh",
    domain: "dohahamadairport.com",
    terminalSummary: "Hamad International Airport is a major Middle East connection hub with extensive long-haul and regional airline operations.",
    trafficSummary: "DOH links Europe, Asia, Africa, Australia, India, and the Americas through highly coordinated connection banks.",
    delayFactors: ["connection waves", "regional weather", "long-haul aircraft rotations"],
    popularSearches: ["Doha airport arrivals", "DOH departures today", "DOH airport live status", "Doha airport delays"],
    routeFocus: ["Delhi", "London", "Bangkok", "Sydney", "New York"],
  },
  {
    code: "IST",
    city: "Istanbul",
    country: "Turkey",
    airportName: "Istanbul Airport",
    slug: "ist",
    domain: "istairport.com",
    terminalSummary: "Istanbul Airport is a major global gateway connecting Europe, Asia, Africa, the Middle East, and the Americas.",
    trafficSummary: "IST handles a huge international route network and dense connection waves throughout the day.",
    delayFactors: ["weather around the Bosphorus region", "large transfer banks", "airspace flow"],
    popularSearches: ["Istanbul airport arrivals", "IST departures today", "IST airport live status", "Istanbul airport delays"],
    routeFocus: ["London", "Dubai", "Delhi", "New York", "Frankfurt"],
  },
  {
    code: "AMS",
    city: "Amsterdam",
    country: "Netherlands",
    airportName: "Amsterdam Airport Schiphol",
    slug: "ams",
    domain: "schiphol.nl",
    terminalSummary: "Amsterdam Schiphol is a major European hub with strong long-haul, Schengen, and intercontinental connection traffic.",
    trafficSummary: "AMS connects Europe with North America, Asia, Africa, and the Middle East through major alliance networks.",
    delayFactors: ["wind and rain", "European flow restrictions", "runway configuration changes"],
    popularSearches: ["Amsterdam airport arrivals", "AMS departures today", "AMS airport live status", "Schiphol delays"],
    routeFocus: ["London", "New York", "Paris", "Dubai", "Delhi"],
  },
  {
    code: "HND",
    city: "Tokyo",
    country: "Japan",
    airportName: "Tokyo Haneda Airport",
    slug: "hnd",
    domain: "tokyo-haneda.com",
    terminalSummary: "Tokyo Haneda is a major Japanese airport close to central Tokyo, serving domestic trunk routes and growing international demand.",
    trafficSummary: "HND is important for Japan domestic travel, East Asia service, North America flights, and premium business routes.",
    delayFactors: ["typhoon season", "dense domestic schedules", "Tokyo airspace flow"],
    popularSearches: ["Haneda arrivals", "HND departures today", "Tokyo Haneda live status", "Haneda airport delays"],
    routeFocus: ["Osaka", "Sapporo", "London", "Singapore", "Los Angeles"],
  },
  {
    code: "ICN",
    city: "Seoul",
    country: "South Korea",
    airportName: "Incheon International Airport",
    slug: "icn",
    domain: "airport.kr",
    terminalSummary: "Incheon International Airport is South Korea's main long-haul gateway and a major Northeast Asia transfer hub.",
    trafficSummary: "ICN connects Korea with Japan, China, Southeast Asia, Europe, North America, and Oceania.",
    delayFactors: ["winter weather", "regional airspace flow", "international transfer waves"],
    popularSearches: ["Incheon arrivals", "ICN departures today", "Seoul airport live status", "Incheon airport delays"],
    routeFocus: ["Tokyo", "Los Angeles", "Singapore", "Bangkok", "London"],
  },
  {
    code: "SYD",
    city: "Sydney",
    country: "Australia",
    airportName: "Sydney Kingsford Smith Airport",
    slug: "syd",
    domain: "sydneyairport.com.au",
    terminalSummary: "Sydney Airport is Australia's busiest airport, handling domestic trunk routes and major international long-haul services.",
    trafficSummary: "SYD links Australia with Asia, the Middle East, North America, New Zealand, and domestic city pairs.",
    delayFactors: ["weather", "curfew-sensitive schedules", "domestic peak periods"],
    popularSearches: ["Sydney airport arrivals", "SYD departures today", "SYD airport live status", "Sydney airport delays"],
    routeFocus: ["Melbourne", "Singapore", "Dubai", "Los Angeles", "Auckland"],
  },
  {
    code: "YYZ",
    city: "Toronto",
    country: "Canada",
    airportName: "Toronto Pearson International Airport",
    slug: "yyz",
    domain: "torontopearson.com",
    terminalSummary: "Toronto Pearson is Canada's largest airport and a key North American hub for domestic, transborder, and international travel.",
    trafficSummary: "YYZ serves Canadian domestic routes, US connections, transatlantic flights, Caribbean service, and long-haul international routes.",
    delayFactors: ["winter operations", "thunderstorms", "US transborder processing waves"],
    popularSearches: ["Toronto Pearson arrivals", "YYZ departures today", "YYZ airport live status", "Toronto airport delays"],
    routeFocus: ["Vancouver", "New York", "London", "Chicago", "Dubai"],
  },
  {
    code: "HKG",
    city: "Hong Kong",
    country: "Hong Kong",
    airportName: "Hong Kong International Airport",
    slug: "hkg",
    domain: "hongkongairport.com",
    terminalSummary: "Hong Kong International Airport is a major Asian hub with strong passenger and cargo connectivity.",
    trafficSummary: "HKG connects East Asia, Southeast Asia, Europe, North America, Australia, and mainland China routes.",
    delayFactors: ["typhoon season", "regional airspace flow", "cargo and passenger bank pressure"],
    popularSearches: ["Hong Kong airport arrivals", "HKG departures today", "HKG airport live status", "Hong Kong airport delays"],
    routeFocus: ["Singapore", "Tokyo", "London", "Sydney", "Bangkok"],
  },
  {
    code: "KUL",
    city: "Kuala Lumpur",
    country: "Malaysia",
    airportName: "Kuala Lumpur International Airport",
    slug: "kul",
    domain: "klia.com.my",
    terminalSummary: "Kuala Lumpur International Airport is Malaysia's main international gateway and a busy Southeast Asia hub.",
    trafficSummary: "KUL supports regional Southeast Asia flights, India links, Middle East connections, and long-haul services.",
    delayFactors: ["tropical storms", "regional connection waves", "low-cost carrier schedule density"],
    popularSearches: ["Kuala Lumpur airport arrivals", "KUL departures today", "KUL airport live status", "KLIA delays"],
    routeFocus: ["Singapore", "Bangkok", "Delhi", "Dubai", "Sydney"],
  },
  {
    code: "MEL",
    city: "Melbourne",
    country: "Australia",
    airportName: "Melbourne Airport",
    slug: "mel",
    domain: "melbourneairport.com.au",
    terminalSummary: "Melbourne Airport is a major Australian domestic and international airport serving Victoria and long-haul travel markets.",
    trafficSummary: "MEL has strong domestic trunk routes and international links to Asia, the Middle East, New Zealand, and North America.",
    delayFactors: ["weather", "domestic peak waves", "international aircraft rotations"],
    popularSearches: ["Melbourne airport arrivals", "MEL departures today", "MEL airport live status", "Melbourne airport delays"],
    routeFocus: ["Sydney", "Singapore", "Dubai", "Auckland", "Los Angeles"],
  },
  {
    code: "SFO",
    city: "San Francisco",
    country: "United States",
    airportName: "San Francisco International Airport",
    slug: "sfo",
    domain: "flysfo.com",
    terminalSummary: "San Francisco International Airport is a major US West Coast gateway for domestic, transpacific, and long-haul international travel.",
    trafficSummary: "SFO connects Northern California with Asia, Europe, Mexico, Canada, and major US domestic hubs.",
    delayFactors: ["coastal fog", "low cloud ceilings", "Bay Area air traffic flow"],
    popularSearches: ["SFO airport arrivals", "SFO departures today", "San Francisco airport live status", "SFO airport delays"],
    routeFocus: ["Los Angeles", "New York", "Tokyo", "London", "Singapore"],
  },
  {
    code: "SEA",
    city: "Seattle",
    country: "United States",
    airportName: "Seattle-Tacoma International Airport",
    slug: "sea",
    domain: "portseattle.org",
    terminalSummary: "Seattle-Tacoma International Airport is a Pacific Northwest hub serving domestic, Alaska, Asia, and Europe routes.",
    trafficSummary: "SEA links Seattle with major US cities, transpacific routes, Canada, Mexico, and European services.",
    delayFactors: ["Pacific Northwest weather", "morning departure banks", "runway flow constraints"],
    popularSearches: ["Seattle airport arrivals", "SEA departures today", "SEA airport live status", "Seattle airport delays"],
    routeFocus: ["Los Angeles", "Anchorage", "New York", "Tokyo", "London"],
  },
  {
    code: "DFW",
    city: "Dallas",
    country: "United States",
    airportName: "Dallas Fort Worth International Airport",
    slug: "dfw",
    domain: "dfwairport.com",
    terminalSummary: "Dallas Fort Worth International Airport is one of the largest US hubs, handling domestic, transborder, and long-haul international traffic.",
    trafficSummary: "DFW connects the central United States with Latin America, Europe, Asia, and high-frequency domestic markets.",
    delayFactors: ["Texas thunderstorms", "large hub banks", "runway and gate flow pressure"],
    popularSearches: ["DFW airport arrivals", "DFW departures today", "Dallas airport live status", "DFW airport delays"],
    routeFocus: ["Los Angeles", "New York", "London", "Mexico City", "Tokyo"],
  },
  {
    code: "DEN",
    city: "Denver",
    country: "United States",
    airportName: "Denver International Airport",
    slug: "den",
    domain: "flydenver.com",
    terminalSummary: "Denver International Airport is a major US mountain-region hub with extensive domestic connections and growing international service.",
    trafficSummary: "DEN handles large domestic connection banks and routes to Canada, Mexico, Europe, and leisure destinations.",
    delayFactors: ["winter snow", "high winds", "hub connection waves"],
    popularSearches: ["Denver airport arrivals", "DEN departures today", "DEN airport live status", "Denver airport delays"],
    routeFocus: ["Chicago", "Los Angeles", "Phoenix", "New York", "London"],
  },
  {
    code: "MIA",
    city: "Miami",
    country: "United States",
    airportName: "Miami International Airport",
    slug: "mia",
    domain: "miami-airport.com",
    terminalSummary: "Miami International Airport is a major gateway for Florida, Latin America, the Caribbean, and long-haul international routes.",
    trafficSummary: "MIA connects North America with South America, Central America, the Caribbean, Europe, and domestic US markets.",
    delayFactors: ["tropical weather", "thunderstorms", "international arrival banks"],
    popularSearches: ["Miami airport arrivals", "MIA departures today", "MIA airport live status", "Miami airport delays"],
    routeFocus: ["New York", "Bogota", "London", "Madrid", "Panama City"],
  },
  {
    code: "MCO",
    city: "Orlando",
    country: "United States",
    airportName: "Orlando International Airport",
    slug: "mco",
    domain: "orlandoairports.net",
    terminalSummary: "Orlando International Airport is a major leisure travel airport serving Central Florida, theme parks, domestic routes, and international visitors.",
    trafficSummary: "MCO supports high-volume US domestic travel, transatlantic leisure service, Latin America routes, and Caribbean connections.",
    delayFactors: ["Florida thunderstorms", "holiday travel peaks", "leisure arrival banks"],
    popularSearches: ["Orlando airport arrivals", "MCO departures today", "MCO airport live status", "Orlando airport delays"],
    routeFocus: ["Atlanta", "New York", "Chicago", "London", "San Juan"],
  },
  {
    code: "LAS",
    city: "Las Vegas",
    country: "United States",
    airportName: "Harry Reid International Airport",
    slug: "las",
    domain: "harryreidairport.com",
    terminalSummary: "Harry Reid International Airport serves Las Vegas leisure, convention, domestic, and international travel demand.",
    trafficSummary: "LAS connects Las Vegas with major US cities, Canada, Mexico, Europe, and high-frequency leisure markets.",
    delayFactors: ["desert winds", "event traffic peaks", "late evening departure banks"],
    popularSearches: ["Las Vegas airport arrivals", "LAS departures today", "LAS airport live status", "Las Vegas airport delays"],
    routeFocus: ["Los Angeles", "New York", "Chicago", "Dallas", "London"],
  },
  {
    code: "PHX",
    city: "Phoenix",
    country: "United States",
    airportName: "Phoenix Sky Harbor International Airport",
    slug: "phx",
    domain: "skyharbor.com",
    terminalSummary: "Phoenix Sky Harbor is a major Southwest US airport with dense domestic networks and regional international routes.",
    trafficSummary: "PHX connects Arizona with major US cities, Mexico, Canada, and Western US leisure destinations.",
    delayFactors: ["summer heat", "monsoon storms", "domestic connection pressure"],
    popularSearches: ["Phoenix airport arrivals", "PHX departures today", "PHX airport live status", "Phoenix airport delays"],
    routeFocus: ["Los Angeles", "Denver", "Seattle", "Chicago", "Dallas"],
  },
  {
    code: "BOS",
    city: "Boston",
    country: "United States",
    airportName: "Boston Logan International Airport",
    slug: "bos",
    domain: "massport.com",
    terminalSummary: "Boston Logan is New England's primary international airport with strong domestic, transatlantic, and business travel demand.",
    trafficSummary: "BOS links Boston with US hubs, Europe, Canada, the Caribbean, and selected long-haul markets.",
    delayFactors: ["winter weather", "coastal storms", "Northeast airspace congestion"],
    popularSearches: ["Boston Logan arrivals", "BOS departures today", "BOS airport live status", "Boston airport delays"],
    routeFocus: ["New York", "London", "Chicago", "Los Angeles", "Dublin"],
  },
  {
    code: "EWR",
    city: "Newark",
    country: "United States",
    airportName: "Newark Liberty International Airport",
    slug: "ewr",
    domain: "newarkairport.com",
    terminalSummary: "Newark Liberty is a major New York-area airport with domestic, transatlantic, and long-haul international service.",
    trafficSummary: "EWR supports large hub operations, European routes, transcontinental service, and New York metropolitan travel demand.",
    delayFactors: ["New York airspace congestion", "winter weather", "runway flow restrictions"],
    popularSearches: ["Newark airport arrivals", "EWR departures today", "EWR airport live status", "Newark airport delays"],
    routeFocus: ["London", "Los Angeles", "Chicago", "San Francisco", "Delhi"],
  },
  {
    code: "YVR",
    city: "Vancouver",
    country: "Canada",
    airportName: "Vancouver International Airport",
    slug: "yvr",
    domain: "yvr.ca",
    terminalSummary: "Vancouver International Airport is a major Canadian gateway for Pacific routes, domestic travel, and North America connections.",
    trafficSummary: "YVR connects Western Canada with Asia, the United States, Europe, Mexico, and domestic Canadian markets.",
    delayFactors: ["Pacific weather", "winter operations", "transpacific connection timing"],
    popularSearches: ["Vancouver airport arrivals", "YVR departures today", "YVR airport live status", "Vancouver airport delays"],
    routeFocus: ["Toronto", "Los Angeles", "Tokyo", "London", "Calgary"],
  },
  {
    code: "MEX",
    city: "Mexico City",
    country: "Mexico",
    airportName: "Mexico City International Airport",
    slug: "mex",
    domain: "aicm.com.mx",
    terminalSummary: "Mexico City International Airport is Mexico's busiest airport, serving domestic, Latin America, North America, and Europe routes.",
    trafficSummary: "MEX handles dense domestic flights, US routes, Central and South America connections, and transatlantic service.",
    delayFactors: ["high-altitude operations", "airspace congestion", "weather and hub banks"],
    popularSearches: ["Mexico City airport arrivals", "MEX departures today", "MEX airport live status", "Mexico City airport delays"],
    routeFocus: ["Cancun", "Los Angeles", "New York", "Madrid", "Bogota"],
  },
  {
    code: "GRU",
    city: "Sao Paulo",
    country: "Brazil",
    airportName: "Sao Paulo Guarulhos International Airport",
    slug: "gru",
    domain: "gru.com.br",
    terminalSummary: "Sao Paulo Guarulhos is Brazil's largest international gateway and a major South American aviation hub.",
    trafficSummary: "GRU connects Brazil with South America, North America, Europe, Africa, and domestic Brazilian markets.",
    delayFactors: ["weather", "international connection banks", "metropolitan airspace flow"],
    popularSearches: ["Sao Paulo airport arrivals", "GRU departures today", "GRU airport live status", "Sao Paulo airport delays"],
    routeFocus: ["Rio de Janeiro", "Miami", "Lisbon", "Madrid", "Buenos Aires"],
  },
  {
    code: "MAD",
    city: "Madrid",
    country: "Spain",
    airportName: "Adolfo Suarez Madrid-Barajas Airport",
    slug: "mad",
    domain: "aena.es",
    terminalSummary: "Madrid-Barajas is Spain's largest airport and a major bridge between Europe and Latin America.",
    trafficSummary: "MAD connects Spain with Europe, Latin America, North America, Africa, and domestic Spanish routes.",
    delayFactors: ["European flow restrictions", "connection waves", "weather"],
    popularSearches: ["Madrid airport arrivals", "MAD departures today", "MAD airport live status", "Madrid airport delays"],
    routeFocus: ["Barcelona", "London", "Mexico City", "New York", "Sao Paulo"],
  },
  {
    code: "BCN",
    city: "Barcelona",
    country: "Spain",
    airportName: "Josep Tarradellas Barcelona-El Prat Airport",
    slug: "bcn",
    domain: "aena.es",
    terminalSummary: "Barcelona-El Prat is a major Mediterranean airport serving leisure, business, European, and long-haul travel.",
    trafficSummary: "BCN links Barcelona with Europe, North Africa, the Middle East, North America, and Spanish domestic markets.",
    delayFactors: ["summer travel peaks", "European flow restrictions", "Mediterranean weather"],
    popularSearches: ["Barcelona airport arrivals", "BCN departures today", "BCN airport live status", "Barcelona airport delays"],
    routeFocus: ["Madrid", "London", "Paris", "Rome", "New York"],
  },
  {
    code: "FCO",
    city: "Rome",
    country: "Italy",
    airportName: "Rome Fiumicino Airport",
    slug: "fco",
    domain: "adr.it",
    terminalSummary: "Rome Fiumicino is Italy's busiest airport, serving domestic, European, Mediterranean, and long-haul routes.",
    trafficSummary: "FCO connects Rome with Europe, North America, the Middle East, Africa, and Italian domestic destinations.",
    delayFactors: ["summer travel demand", "European airspace flow", "connection waves"],
    popularSearches: ["Rome airport arrivals", "FCO departures today", "FCO airport live status", "Rome airport delays"],
    routeFocus: ["Milan", "London", "New York", "Dubai", "Paris"],
  },
  {
    code: "ZRH",
    city: "Zurich",
    country: "Switzerland",
    airportName: "Zurich Airport",
    slug: "zrh",
    domain: "zurich-airport.com",
    terminalSummary: "Zurich Airport is Switzerland's largest airport and a key European hub for business, leisure, and long-haul connections.",
    trafficSummary: "ZRH connects Switzerland with Europe, North America, Asia, the Middle East, and premium business markets.",
    delayFactors: ["winter weather", "Alpine weather patterns", "European flow restrictions"],
    popularSearches: ["Zurich airport arrivals", "ZRH departures today", "ZRH airport live status", "Zurich airport delays"],
    routeFocus: ["London", "New York", "Frankfurt", "Dubai", "Singapore"],
  },
  {
    code: "JNB",
    city: "Johannesburg",
    country: "South Africa",
    airportName: "O. R. Tambo International Airport",
    slug: "jnb",
    domain: "airports.co.za",
    terminalSummary: "O. R. Tambo International Airport is South Africa's busiest airport and a major African long-haul gateway.",
    trafficSummary: "JNB connects Southern Africa with Europe, the Middle East, Asia, North America, and domestic South African routes.",
    delayFactors: ["thunderstorms", "long-haul rotation timing", "regional connection waves"],
    popularSearches: ["Johannesburg airport arrivals", "JNB departures today", "JNB airport live status", "Johannesburg airport delays"],
    routeFocus: ["Cape Town", "Dubai", "London", "Doha", "Frankfurt"],
  },
  {
    code: "CAI",
    city: "Cairo",
    country: "Egypt",
    airportName: "Cairo International Airport",
    slug: "cai",
    domain: "cairo-airport.com",
    terminalSummary: "Cairo International Airport is Egypt's main international airport and a key North Africa and Middle East connection point.",
    trafficSummary: "CAI links Egypt with Europe, Africa, the Middle East, Asia, and domestic Egyptian destinations.",
    delayFactors: ["regional connection banks", "weather visibility", "long-haul rotations"],
    popularSearches: ["Cairo airport arrivals", "CAI departures today", "CAI airport live status", "Cairo airport delays"],
    routeFocus: ["Dubai", "Jeddah", "London", "Paris", "Istanbul"],
  },
  {
    code: "ADD",
    city: "Addis Ababa",
    country: "Ethiopia",
    airportName: "Addis Ababa Bole International Airport",
    slug: "add",
    domain: "ethiopianairlines.com",
    terminalSummary: "Addis Ababa Bole International Airport is a major East African aviation hub with extensive regional and long-haul connectivity.",
    trafficSummary: "ADD connects Africa with Europe, the Middle East, Asia, North America, and regional African destinations.",
    delayFactors: ["connection bank pressure", "regional weather", "long-haul aircraft rotations"],
    popularSearches: ["Addis Ababa airport arrivals", "ADD departures today", "ADD airport live status", "Addis Ababa airport delays"],
    routeFocus: ["Nairobi", "Dubai", "London", "Mumbai", "Johannesburg"],
  },
  {
    code: "NBO",
    city: "Nairobi",
    country: "Kenya",
    airportName: "Jomo Kenyatta International Airport",
    slug: "nbo",
    domain: "kaa.go.ke",
    terminalSummary: "Jomo Kenyatta International Airport is Kenya's primary international airport and a major East African gateway.",
    trafficSummary: "NBO connects Kenya with Africa, Europe, the Middle East, India, and domestic Kenyan destinations.",
    delayFactors: ["regional weather", "international arrival banks", "runway and terminal flow"],
    popularSearches: ["Nairobi airport arrivals", "NBO departures today", "NBO airport live status", "Nairobi airport delays"],
    routeFocus: ["Mombasa", "Dubai", "London", "Addis Ababa", "Doha"],
  },
  {
    code: "RUH",
    city: "Riyadh",
    country: "Saudi Arabia",
    airportName: "King Khalid International Airport",
    slug: "ruh",
    domain: "kkia.sa",
    terminalSummary: "King Khalid International Airport serves Riyadh with domestic Saudi routes, Gulf connections, and growing long-haul service.",
    trafficSummary: "RUH links Saudi Arabia with the Middle East, India, Europe, Asia, and domestic Saudi city pairs.",
    delayFactors: ["regional weather", "peak departure waves", "domestic connection pressure"],
    popularSearches: ["Riyadh airport arrivals", "RUH departures today", "RUH airport live status", "Riyadh airport delays"],
    routeFocus: ["Jeddah", "Dubai", "Delhi", "London", "Cairo"],
  },
  {
    code: "JED",
    city: "Jeddah",
    country: "Saudi Arabia",
    airportName: "King Abdulaziz International Airport",
    slug: "jed",
    domain: "jed-airport.com",
    terminalSummary: "King Abdulaziz International Airport serves Jeddah, the western Saudi region, Red Sea travel, and pilgrimage traffic.",
    trafficSummary: "JED connects Saudi Arabia with the Middle East, Africa, South Asia, Europe, and heavy domestic demand.",
    delayFactors: ["pilgrimage travel peaks", "regional weather", "large international arrival waves"],
    popularSearches: ["Jeddah airport arrivals", "JED departures today", "JED airport live status", "Jeddah airport delays"],
    routeFocus: ["Riyadh", "Dubai", "Cairo", "Delhi", "Istanbul"],
  },
  {
    code: "DPS",
    city: "Bali",
    country: "Indonesia",
    airportName: "I Gusti Ngurah Rai International Airport",
    slug: "dps",
    domain: "bali-airport.com",
    terminalSummary: "I Gusti Ngurah Rai International Airport is Bali's main airport and a major leisure travel gateway in Indonesia.",
    trafficSummary: "DPS connects Bali with Southeast Asia, Australia, East Asia, the Middle East, and domestic Indonesian routes.",
    delayFactors: ["tropical weather", "holiday peaks", "international leisure arrival waves"],
    popularSearches: ["Bali airport arrivals", "DPS departures today", "DPS airport live status", "Bali airport delays"],
    routeFocus: ["Singapore", "Sydney", "Kuala Lumpur", "Jakarta", "Doha"],
  },
  {
    code: "CGK",
    city: "Jakarta",
    country: "Indonesia",
    airportName: "Soekarno-Hatta International Airport",
    slug: "cgk",
    domain: "soekarnohatta-airport.co.id",
    terminalSummary: "Soekarno-Hatta International Airport is Indonesia's busiest airport and a major Southeast Asian domestic and international hub.",
    trafficSummary: "CGK connects Jakarta with Indonesia's domestic network, Southeast Asia, East Asia, the Middle East, and Australia.",
    delayFactors: ["tropical storms", "domestic hub banks", "Jakarta airspace congestion"],
    popularSearches: ["Jakarta airport arrivals", "CGK departures today", "CGK airport live status", "Jakarta airport delays"],
    routeFocus: ["Bali", "Singapore", "Kuala Lumpur", "Doha", "Tokyo"],
  },
  {
    code: "CCU",
    city: "Kolkata",
    country: "India",
    airportName: "Netaji Subhas Chandra Bose International Airport",
    slug: "ccu",
    domain: "aai.aero",
    terminalSummary: "Kolkata Airport is the main aviation gateway for eastern India, serving domestic metro routes, Northeast India connections, and international services.",
    trafficSummary: "CCU connects Kolkata with Delhi, Mumbai, Bangalore, Chennai, Southeast Asia, the Middle East, and regional Indian cities.",
    delayFactors: ["monsoon weather", "evening departure waves", "regional aircraft rotations"],
    popularSearches: ["Kolkata airport arrivals", "CCU departures today", "CCU airport live status", "Kolkata airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Bangkok", "Dubai"],
  },
  {
    code: "COK",
    city: "Kochi",
    country: "India",
    airportName: "Cochin International Airport",
    slug: "cok",
    domain: "cial.aero",
    terminalSummary: "Cochin International Airport is a major Kerala gateway with strong Gulf traffic, domestic service, and international leisure demand.",
    trafficSummary: "COK links Kerala with Gulf hubs, Indian metros, Southeast Asia, and regional domestic destinations.",
    delayFactors: ["monsoon rain", "Gulf departure banks", "international aircraft rotations"],
    popularSearches: ["Kochi airport arrivals", "COK departures today", "COK airport live status", "Kochi airport delays"],
    routeFocus: ["Dubai", "Doha", "Delhi", "Mumbai", "Bangalore"],
  },
  {
    code: "GOI",
    city: "Goa",
    country: "India",
    airportName: "Goa Dabolim Airport",
    slug: "goi",
    domain: "aai.aero",
    terminalSummary: "Goa Dabolim Airport serves leisure, domestic, charter, and regional international demand for Goa.",
    trafficSummary: "GOI connects Goa with Indian metros, seasonal leisure markets, and selected international routes.",
    delayFactors: ["holiday peaks", "monsoon weather", "slot and runway constraints"],
    popularSearches: ["Goa airport arrivals", "GOI departures today", "GOI airport live status", "Goa airport delays"],
    routeFocus: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Dubai"],
  },
  {
    code: "GOX",
    city: "North Goa",
    country: "India",
    airportName: "Manohar International Airport",
    slug: "gox",
    domain: "newgoaairport.com",
    terminalSummary: "Manohar International Airport supports North Goa travel with expanding domestic and international leisure services.",
    trafficSummary: "GOX connects Goa with major Indian metros, leisure markets, and growing international demand.",
    delayFactors: ["holiday travel peaks", "monsoon weather", "new route schedule changes"],
    popularSearches: ["North Goa airport arrivals", "GOX departures today", "GOX airport live status", "Mopa airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Hyderabad", "Pune"],
  },
  {
    code: "PNQ",
    city: "Pune",
    country: "India",
    airportName: "Pune International Airport",
    slug: "pnq",
    domain: "aai.aero",
    terminalSummary: "Pune Airport serves a major business, education, technology, and leisure market in western India.",
    trafficSummary: "PNQ links Pune with Delhi, Bangalore, Hyderabad, Chennai, Kolkata, Goa, and selected international services.",
    delayFactors: ["slot constraints", "business travel peaks", "weather and aircraft rotation pressure"],
    popularSearches: ["Pune airport arrivals", "PNQ departures today", "PNQ airport live status", "Pune airport delays"],
    routeFocus: ["Delhi", "Bangalore", "Hyderabad", "Chennai", "Goa"],
  },
  {
    code: "AMD",
    city: "Ahmedabad",
    country: "India",
    airportName: "Sardar Vallabhbhai Patel International Airport",
    slug: "amd",
    domain: "adani.com",
    terminalSummary: "Ahmedabad Airport is a major Gujarat gateway with domestic metro service and important Gulf and international connectivity.",
    trafficSummary: "AMD connects Ahmedabad with Indian metros, Dubai, Abu Dhabi, Doha, Southeast Asia, and regional business markets.",
    delayFactors: ["peak departure banks", "weather visibility", "international aircraft rotations"],
    popularSearches: ["Ahmedabad airport arrivals", "AMD departures today", "AMD airport live status", "Ahmedabad airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Dubai", "Doha", "Bangalore"],
  },
  {
    code: "JAI",
    city: "Jaipur",
    country: "India",
    airportName: "Jaipur International Airport",
    slug: "jai",
    domain: "jaipurairport.com",
    terminalSummary: "Jaipur Airport serves Rajasthan tourism, domestic metro routes, and selected international connections.",
    trafficSummary: "JAI connects Jaipur with Delhi, Mumbai, Bangalore, Hyderabad, Dubai, Sharjah, and leisure markets.",
    delayFactors: ["tourism peaks", "winter visibility", "regional aircraft rotations"],
    popularSearches: ["Jaipur airport arrivals", "JAI departures today", "JAI airport live status", "Jaipur airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Dubai", "Hyderabad"],
  },
  {
    code: "LKO",
    city: "Lucknow",
    country: "India",
    airportName: "Chaudhary Charan Singh International Airport",
    slug: "lko",
    domain: "adani.com",
    terminalSummary: "Lucknow Airport is a major Uttar Pradesh gateway with domestic routes and Gulf-focused international traffic.",
    trafficSummary: "LKO connects Lucknow with Delhi, Mumbai, Bangalore, Hyderabad, Kolkata, Dubai, and other Gulf destinations.",
    delayFactors: ["winter fog", "evening departures", "regional flow into North India"],
    popularSearches: ["Lucknow airport arrivals", "LKO departures today", "LKO airport live status", "Lucknow airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Dubai", "Hyderabad"],
  },
  {
    code: "TRV",
    city: "Thiruvananthapuram",
    country: "India",
    airportName: "Thiruvananthapuram International Airport",
    slug: "trv",
    domain: "trivandrumairport.com",
    terminalSummary: "Thiruvananthapuram Airport is an important Kerala gateway with domestic, Gulf, and South India travel demand.",
    trafficSummary: "TRV connects Kerala with Indian metros, Gulf hubs, and regional international destinations.",
    delayFactors: ["monsoon weather", "Gulf departure banks", "coastal operations"],
    popularSearches: ["Thiruvananthapuram airport arrivals", "TRV departures today", "TRV airport live status", "Trivandrum airport delays"],
    routeFocus: ["Dubai", "Doha", "Delhi", "Bangalore", "Mumbai"],
  },
  {
    code: "IXC",
    city: "Chandigarh",
    country: "India",
    airportName: "Shaheed Bhagat Singh International Airport",
    slug: "ixc",
    domain: "chandigarhinternationalairport.in",
    terminalSummary: "Chandigarh Airport serves Chandigarh, Mohali, Panchkula, Punjab, Haryana, and Himachal Pradesh travel demand.",
    trafficSummary: "IXC connects North India with Delhi, Mumbai, Bangalore, Hyderabad, Srinagar, and selected regional markets.",
    delayFactors: ["winter fog", "northern airspace flow", "regional weather"],
    popularSearches: ["Chandigarh airport arrivals", "IXC departures today", "IXC airport live status", "Chandigarh airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Srinagar", "Hyderabad"],
  },
  {
    code: "BBI",
    city: "Bhubaneswar",
    country: "India",
    airportName: "Biju Patnaik International Airport",
    slug: "bbi",
    domain: "aai.aero",
    terminalSummary: "Bhubaneswar Airport is Odisha's key aviation gateway, serving domestic metro routes and growing regional demand.",
    trafficSummary: "BBI connects Odisha with Delhi, Mumbai, Bangalore, Kolkata, Hyderabad, and selected international services.",
    delayFactors: ["monsoon weather", "regional aircraft rotations", "evening departures"],
    popularSearches: ["Bhubaneswar airport arrivals", "BBI departures today", "BBI airport live status", "Bhubaneswar airport delays"],
    routeFocus: ["Delhi", "Kolkata", "Bangalore", "Mumbai", "Hyderabad"],
  },
  {
    code: "GAU",
    city: "Guwahati",
    country: "India",
    airportName: "Lokpriya Gopinath Bordoloi International Airport",
    slug: "gau",
    domain: "adani.com",
    terminalSummary: "Guwahati Airport is the primary aviation gateway for Assam and much of Northeast India.",
    trafficSummary: "GAU connects Northeast India with Delhi, Kolkata, Mumbai, Bangalore, Imphal, Agartala, and regional markets.",
    delayFactors: ["monsoon weather", "regional terrain weather", "Northeast India aircraft rotations"],
    popularSearches: ["Guwahati airport arrivals", "GAU departures today", "GAU airport live status", "Guwahati airport delays"],
    routeFocus: ["Delhi", "Kolkata", "Mumbai", "Bangalore", "Imphal"],
  },
  {
    code: "PAT",
    city: "Patna",
    country: "India",
    airportName: "Jay Prakash Narayan Airport",
    slug: "pat",
    domain: "aai.aero",
    terminalSummary: "Patna Airport serves Bihar with dense domestic demand and frequent links to India's major metros.",
    trafficSummary: "PAT connects Patna with Delhi, Mumbai, Bangalore, Kolkata, Hyderabad, Pune, and other domestic cities.",
    delayFactors: ["winter fog", "runway and slot constraints", "North India flow restrictions"],
    popularSearches: ["Patna airport arrivals", "PAT departures today", "PAT airport live status", "Patna airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Hyderabad"],
  },
  {
    code: "IXB",
    city: "Bagdogra",
    country: "India",
    airportName: "Bagdogra Airport",
    slug: "ixb",
    domain: "aai.aero",
    terminalSummary: "Bagdogra Airport serves North Bengal, Sikkim, Darjeeling, and Himalayan leisure travel demand.",
    trafficSummary: "IXB connects the region with Kolkata, Delhi, Mumbai, Bangalore, Hyderabad, and other domestic markets.",
    delayFactors: ["mountain-region weather", "fog and visibility", "tourism peak pressure"],
    popularSearches: ["Bagdogra airport arrivals", "IXB departures today", "IXB airport live status", "Bagdogra airport delays"],
    routeFocus: ["Kolkata", "Delhi", "Mumbai", "Bangalore", "Hyderabad"],
  },
  {
    code: "IXR",
    city: "Ranchi",
    country: "India",
    airportName: "Birsa Munda Airport",
    slug: "ixr",
    domain: "aai.aero",
    terminalSummary: "Ranchi Airport serves Jharkhand with domestic metro connectivity and regional travel demand.",
    trafficSummary: "IXR connects Ranchi with Delhi, Kolkata, Mumbai, Bangalore, Hyderabad, and other domestic destinations.",
    delayFactors: ["monsoon weather", "regional aircraft rotations", "evening departure pressure"],
    popularSearches: ["Ranchi airport arrivals", "IXR departures today", "IXR airport live status", "Ranchi airport delays"],
    routeFocus: ["Delhi", "Kolkata", "Mumbai", "Bangalore", "Hyderabad"],
  },
];

export function getAirportSeoProfile(code: string) {
  return airportSeoProfiles.find((airport) => airport.code === code.toUpperCase()) ?? null;
}
