export type AirportSeoProfile = {
  code: string;
  city: string;
  country: string;
  airportName: string;
  slug: string;
  domain: string;
  terminalSummary: string;
  trafficSummary: string;
  delayFactors: string[];
  popularSearches: string[];
  routeFocus: string[];
};

export const airportSeoProfiles: AirportSeoProfile[] = [
  {
    code: "DEL",
    city: "Delhi",
    country: "India",
    airportName: "Indira Gandhi International Airport",
    slug: "del",
    domain: "newdelhiairport.in",
    terminalSummary:
      "Delhi Airport is one of India's busiest international gateways, with domestic and international operations across large terminal facilities serving North India, NCR business travel, and long-haul connections.",
    trafficSummary:
      "The airport is a major hub for Indian domestic routes and a strong origin point for flights to the Middle East, Southeast Asia, Europe, and North America.",
    delayFactors: ["winter fog and low visibility", "peak evening departures", "air traffic flow into North India"],
    popularSearches: ["Delhi airport arrivals", "Delhi airport departures today", "DEL airport live status", "Delhi airport delays"],
    routeFocus: ["Mumbai", "Bangalore", "Dubai", "London", "Singapore"],
  },
  {
    code: "BOM",
    city: "Mumbai",
    country: "India",
    airportName: "Chhatrapati Shivaji Maharaj International Airport",
    slug: "bom",
    domain: "csmia.adaniairports.com",
    terminalSummary:
      "Mumbai Airport serves India's financial capital with dense domestic schedules, international long-haul service, and heavy business travel demand.",
    trafficSummary:
      "Mumbai is a key connection point for western India, with frequent flights to Delhi, Bangalore, Goa, Dubai, London, and major Indian metros.",
    delayFactors: ["monsoon weather", "single-airport congestion", "late-night international arrival banks"],
    popularSearches: ["Mumbai airport arrivals", "Mumbai departure today", "BOM airport live status", "Mumbai airport delays"],
    routeFocus: ["Delhi", "Bangalore", "Goa", "Dubai", "London"],
  },
  {
    code: "BLR",
    city: "Bangalore",
    country: "India",
    airportName: "Kempegowda International Airport Bengaluru",
    slug: "blr",
    domain: "bengaluruairport.com",
    terminalSummary:
      "Bangalore Airport supports India's technology capital with domestic business traffic, international departures, and expanding terminal capacity.",
    trafficSummary:
      "The airport is a strong southern India hub, especially for routes to Delhi, Mumbai, Hyderabad, Singapore, Dubai, and European connections.",
    delayFactors: ["evening thunderstorm activity", "surface traffic around airport access roads", "peak business travel waves"],
    popularSearches: ["Bangalore airport arrivals", "Bangalore airport departures", "BLR airport live status", "Bangalore airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Hyderabad", "Singapore", "Dubai"],
  },
  {
    code: "HYD",
    city: "Hyderabad",
    country: "India",
    airportName: "Rajiv Gandhi International Airport",
    slug: "hyd",
    domain: "hyderabad.aero",
    terminalSummary:
      "Hyderabad Airport is a major central-southern India airport serving domestic routes, Gulf connections, technology travel, and cargo-linked aviation demand.",
    trafficSummary:
      "Hyderabad has frequent service to Indian metros and international links to the Middle East, Southeast Asia, and selected long-haul markets.",
    delayFactors: ["late evening connection banks", "seasonal storms", "airport slot and turnaround pressure"],
    popularSearches: ["Hyderabad airport arrivals", "Hyderabad airport departures today", "HYD live flight status", "Hyderabad airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangalore", "Dubai", "Doha"],
  },
  {
    code: "MAA",
    city: "Chennai",
    country: "India",
    airportName: "Chennai International Airport",
    slug: "maa",
    domain: "aai.aero",
    terminalSummary:
      "Chennai Airport is a major gateway for Tamil Nadu, South India business routes, Southeast Asia services, and Gulf-bound travel.",
    trafficSummary:
      "Chennai handles strong domestic demand and international routes to Singapore, Kuala Lumpur, Dubai, Doha, and other regional hubs.",
    delayFactors: ["coastal weather", "monsoon disruption", "international departure bank congestion"],
    popularSearches: ["Chennai airport arrivals", "Chennai airport departures", "MAA airport live status", "Chennai airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Singapore", "Dubai", "Kuala Lumpur"],
  },
  {
    code: "DXB",
    city: "Dubai",
    country: "United Arab Emirates",
    airportName: "Dubai International Airport",
    slug: "dxb",
    domain: "dubaiairports.ae",
    terminalSummary:
      "Dubai International is one of the world's most important long-haul hubs, connecting Europe, Asia, Africa, the Middle East, Australia, and the Americas.",
    trafficSummary:
      "DXB is built around major international connection banks, high-frequency Emirates operations, and dense regional airline activity.",
    delayFactors: ["large connection waves", "regional weather and visibility", "high runway utilization"],
    popularSearches: ["Dubai airport arrivals", "Dubai airport departures today", "DXB airport live status", "Dubai airport delays"],
    routeFocus: ["Delhi", "London", "Singapore", "Bangkok", "New York"],
  },
  {
    code: "SIN",
    city: "Singapore",
    country: "Singapore",
    airportName: "Singapore Changi Airport",
    slug: "sin",
    domain: "changiairport.com",
    terminalSummary:
      "Singapore Changi is a premier Southeast Asia hub with extensive international connections, efficient terminals, and strong long-haul airline networks.",
    trafficSummary:
      "Changi links Southeast Asia with India, China, Australia, Europe, the Middle East, and North America through frequent regional and long-haul services.",
    delayFactors: ["regional thunderstorm cells", "connection bank pressure", "airspace flow around Southeast Asia"],
    popularSearches: ["Singapore airport arrivals", "Changi departures today", "SIN airport live status", "Singapore airport delays"],
    routeFocus: ["Delhi", "Mumbai", "Bangkok", "London", "Sydney"],
  },
  {
    code: "BKK",
    city: "Bangkok",
    country: "Thailand",
    airportName: "Suvarnabhumi Airport",
    slug: "bkk",
    domain: "suvarnabhumi.airportthai.co.th",
    terminalSummary:
      "Bangkok Suvarnabhumi is Thailand's main international airport and a major Southeast Asia gateway for leisure, business, and regional transfer traffic.",
    trafficSummary:
      "BKK connects Thailand with India, East Asia, the Middle East, Europe, and domestic Thai destinations through dense regional schedules.",
    delayFactors: ["monsoon storms", "tourism peak periods", "regional arrival and departure waves"],
    popularSearches: ["Bangkok airport arrivals", "Bangkok departures today", "BKK airport live status", "Bangkok airport delays"],
    routeFocus: ["Singapore", "Delhi", "Dubai", "London", "Phuket"],
  },
  {
    code: "LHR",
    city: "London",
    country: "United Kingdom",
    airportName: "London Heathrow Airport",
    slug: "lhr",
    domain: "heathrow.com",
    terminalSummary:
      "London Heathrow is the United Kingdom's largest international airport and one of Europe's most important long-haul connection points.",
    trafficSummary:
      "Heathrow has heavy transatlantic demand, European feeder traffic, India links, Middle East connections, and global premium travel flows.",
    delayFactors: ["European air traffic restrictions", "weather and wind patterns", "slot-controlled runway operations"],
    popularSearches: ["London Heathrow arrivals", "London Heathrow departures today", "LHR airport live status", "Heathrow airport delays"],
    routeFocus: ["New York", "Delhi", "Dubai", "Singapore", "Mumbai"],
  },
  {
    code: "JFK",
    city: "New York",
    country: "United States",
    airportName: "John F. Kennedy International Airport",
    slug: "jfk",
    domain: "jfkairport.com",
    terminalSummary:
      "New York JFK is a major international gateway for the United States, with strong transatlantic, transcontinental, Caribbean, and long-haul service.",
    trafficSummary:
      "JFK serves high-volume international arrivals and departures, premium long-haul routes, and important domestic feeder connections.",
    delayFactors: ["New York airspace congestion", "winter weather", "terminal and runway flow restrictions"],
    popularSearches: ["JFK airport arrivals", "JFK departures today", "New York airport live status", "JFK airport delays"],
    routeFocus: ["London", "Dubai", "Delhi", "Los Angeles", "Paris"],
  },
  {
    code: "LAX",
    city: "Los Angeles",
    country: "United States",
    airportName: "Los Angeles International Airport",
    slug: "lax",
    domain: "flylax.com",
    terminalSummary: "Los Angeles International Airport is a major US West Coast gateway with domestic, transpacific, Latin America, and long-haul international service.",
    trafficSummary: "LAX handles heavy entertainment, business, leisure, and connecting demand across North America, Asia, Australia, Europe, and Latin America.",
    delayFactors: ["coastal weather", "Los Angeles basin congestion", "international arrival banks"],
    popularSearches: ["LAX airport arrivals", "LAX departures today", "Los Angeles airport live status", "LAX airport delays"],
    routeFocus: ["New York", "London", "Tokyo", "Sydney", "Mexico City"],
  },
  {
    code: "ORD",
    city: "Chicago",
    country: "United States",
    airportName: "Chicago O'Hare International Airport",
    slug: "ord",
    domain: "flychicago.com",
    terminalSummary: "Chicago O'Hare is one of the busiest hub airports in North America, supporting dense domestic networks and long-haul international service.",
    trafficSummary: "ORD is a major connecting hub for US domestic flights, transatlantic routes, Latin America service, and Asia links.",
    delayFactors: ["winter weather", "thunderstorms", "hub bank congestion"],
    popularSearches: ["Chicago O'Hare arrivals", "ORD departures today", "ORD airport live status", "Chicago airport delays"],
    routeFocus: ["New York", "Los Angeles", "London", "Toronto", "Tokyo"],
  },
  {
    code: "ATL",
    city: "Atlanta",
    country: "United States",
    airportName: "Hartsfield-Jackson Atlanta International Airport",
    slug: "atl",
    domain: "atl.com",
    terminalSummary: "Atlanta Airport is a massive US hub with high-frequency domestic banks and international routes across the Americas, Europe, Africa, and beyond.",
    trafficSummary: "ATL is built for large-scale connections, making live arrivals, departures, and delay awareness especially useful.",
    delayFactors: ["summer thunderstorms", "connection bank pressure", "high runway utilization"],
    popularSearches: ["Atlanta airport arrivals", "ATL departures today", "ATL airport live status", "Atlanta airport delays"],
    routeFocus: ["New York", "Orlando", "London", "Paris", "Los Angeles"],
  },
  {
    code: "CDG",
    city: "Paris",
    country: "France",
    airportName: "Paris Charles de Gaulle Airport",
    slug: "cdg",
    domain: "parisaeroport.fr",
    terminalSummary: "Paris Charles de Gaulle is France's largest international airport and a major European long-haul and Schengen connection hub.",
    trafficSummary: "CDG connects Europe with North America, Africa, the Middle East, India, and Asia through large airline alliance networks.",
    delayFactors: ["European airspace flow", "weather", "terminal connection waves"],
    popularSearches: ["Paris CDG arrivals", "CDG departures today", "CDG airport live status", "Paris airport delays"],
    routeFocus: ["London", "New York", "Dubai", "Delhi", "Tokyo"],
  },
  {
    code: "FRA",
    city: "Frankfurt",
    country: "Germany",
    airportName: "Frankfurt Airport",
    slug: "fra",
    domain: "frankfurt-airport.com",
    terminalSummary: "Frankfurt Airport is Germany's busiest aviation hub, known for long-haul connectivity, European feeder flights, and cargo operations.",
    trafficSummary: "FRA supports major connections across Europe, North America, India, the Middle East, East Asia, and Africa.",
    delayFactors: ["weather", "European air traffic restrictions", "large connection banks"],
    popularSearches: ["Frankfurt airport arrivals", "FRA departures today", "FRA airport live status", "Frankfurt airport delays"],
    routeFocus: ["London", "Delhi", "New York", "Singapore", "Dubai"],
  },
  {
    code: "DOH",
    city: "Doha",
    country: "Qatar",
    airportName: "Hamad International Airport",
    slug: "doh",
    domain: "dohahamadairport.com",
    terminalSummary: "Hamad International Airport is a major Middle East connection hub with extensive long-haul and regional airline operations.",
    trafficSummary: "DOH links Europe, Asia, Africa, Australia, India, and the Americas through highly coordinated connection banks.",
    delayFactors: ["connection waves", "regional weather", "long-haul aircraft rotations"],
    popularSearches: ["Doha airport arrivals", "DOH departures today", "DOH airport live status", "Doha airport delays"],
    routeFocus: ["Delhi", "London", "Bangkok", "Sydney", "New York"],
  },
  {
    code: "IST",
    city: "Istanbul",
    country: "Turkey",
    airportName: "Istanbul Airport",
    slug: "ist",
    domain: "istairport.com",
    terminalSummary: "Istanbul Airport is a major global gateway connecting Europe, Asia, Africa, the Middle East, and the Americas.",
    trafficSummary: "IST handles a huge international route network and dense connection waves throughout the day.",
    delayFactors: ["weather around the Bosphorus region", "large transfer banks", "airspace flow"],
    popularSearches: ["Istanbul airport arrivals", "IST departures today", "IST airport live status", "Istanbul airport delays"],
    routeFocus: ["London", "Dubai", "Delhi", "New York", "Frankfurt"],
  },
  {
    code: "AMS",
    city: "Amsterdam",
    country: "Netherlands",
    airportName: "Amsterdam Airport Schiphol",
    slug: "ams",
    domain: "schiphol.nl",
    terminalSummary: "Amsterdam Schiphol is a major European hub with strong long-haul, Schengen, and intercontinental connection traffic.",
    trafficSummary: "AMS connects Europe with North America, Asia, Africa, and the Middle East through major alliance networks.",
    delayFactors: ["wind and rain", "European flow restrictions", "runway configuration changes"],
    popularSearches: ["Amsterdam airport arrivals", "AMS departures today", "AMS airport live status", "Schiphol delays"],
    routeFocus: ["London", "New York", "Paris", "Dubai", "Delhi"],
  },
  {
    code: "HND",
    city: "Tokyo",
    country: "Japan",
    airportName: "Tokyo Haneda Airport",
    slug: "hnd",
    domain: "tokyo-haneda.com",
    terminalSummary: "Tokyo Haneda is a major Japanese airport close to central Tokyo, serving domestic trunk routes and growing international demand.",
    trafficSummary: "HND is important for Japan domestic travel, East Asia service, North America flights, and premium business routes.",
    delayFactors: ["typhoon season", "dense domestic schedules", "Tokyo airspace flow"],
    popularSearches: ["Haneda arrivals", "HND departures today", "Tokyo Haneda live status", "Haneda airport delays"],
    routeFocus: ["Osaka", "Sapporo", "London", "Singapore", "Los Angeles"],
  },
  {
    code: "ICN",
    city: "Seoul",
    country: "South Korea",
    airportName: "Incheon International Airport",
    slug: "icn",
    domain: "airport.kr",
    terminalSummary: "Incheon International Airport is South Korea's main long-haul gateway and a major Northeast Asia transfer hub.",
    trafficSummary: "ICN connects Korea with Japan, China, Southeast Asia, Europe, North America, and Oceania.",
    delayFactors: ["winter weather", "regional airspace flow", "international transfer waves"],
    popularSearches: ["Incheon arrivals", "ICN departures today", "Seoul airport live status", "Incheon airport delays"],
    routeFocus: ["Tokyo", "Los Angeles", "Singapore", "Bangkok", "London"],
  },
  {
    code: "SYD",
    city: "Sydney",
    country: "Australia",
    airportName: "Sydney Kingsford Smith Airport",
    slug: "syd",
    domain: "sydneyairport.com.au",
    terminalSummary: "Sydney Airport is Australia's busiest airport, handling domestic trunk routes and major international long-haul services.",
    trafficSummary: "SYD links Australia with Asia, the Middle East, North America, New Zealand, and domestic city pairs.",
    delayFactors: ["weather", "curfew-sensitive schedules", "domestic peak periods"],
    popularSearches: ["Sydney airport arrivals", "SYD departures today", "SYD airport live status", "Sydney airport delays"],
    routeFocus: ["Melbourne", "Singapore", "Dubai", "Los Angeles", "Auckland"],
  },
  {
    code: "YYZ",
    city: "Toronto",
    country: "Canada",
    airportName: "Toronto Pearson International Airport",
    slug: "yyz",
    domain: "torontopearson.com",
    terminalSummary: "Toronto Pearson is Canada's largest airport and a key North American hub for domestic, transborder, and international travel.",
    trafficSummary: "YYZ serves Canadian domestic routes, US connections, transatlantic flights, Caribbean service, and long-haul international routes.",
    delayFactors: ["winter operations", "thunderstorms", "US transborder processing waves"],
    popularSearches: ["Toronto Pearson arrivals", "YYZ departures today", "YYZ airport live status", "Toronto airport delays"],
    routeFocus: ["Vancouver", "New York", "London", "Chicago", "Dubai"],
  },
  {
    code: "HKG",
    city: "Hong Kong",
    country: "Hong Kong",
    airportName: "Hong Kong International Airport",
    slug: "hkg",
    domain: "hongkongairport.com",
    terminalSummary: "Hong Kong International Airport is a major Asian hub with strong passenger and cargo connectivity.",
    trafficSummary: "HKG connects East Asia, Southeast Asia, Europe, North America, Australia, and mainland China routes.",
    delayFactors: ["typhoon season", "regional airspace flow", "cargo and passenger bank pressure"],
    popularSearches: ["Hong Kong airport arrivals", "HKG departures today", "HKG airport live status", "Hong Kong airport delays"],
    routeFocus: ["Singapore", "Tokyo", "London", "Sydney", "Bangkok"],
  },
  {
    code: "KUL",
    city: "Kuala Lumpur",
    country: "Malaysia",
    airportName: "Kuala Lumpur International Airport",
    slug: "kul",
    domain: "klia.com.my",
    terminalSummary: "Kuala Lumpur International Airport is Malaysia's main international gateway and a busy Southeast Asia hub.",
    trafficSummary: "KUL supports regional Southeast Asia flights, India links, Middle East connections, and long-haul services.",
    delayFactors: ["tropical storms", "regional connection waves", "low-cost carrier schedule density"],
    popularSearches: ["Kuala Lumpur airport arrivals", "KUL departures today", "KUL airport live status", "KLIA delays"],
    routeFocus: ["Singapore", "Bangkok", "Delhi", "Dubai", "Sydney"],
  },
  {
    code: "MEL",
    city: "Melbourne",
    country: "Australia",
    airportName: "Melbourne Airport",
    slug: "mel",
    domain: "melbourneairport.com.au",
    terminalSummary: "Melbourne Airport is a major Australian domestic and international airport serving Victoria and long-haul travel markets.",
    trafficSummary: "MEL has strong domestic trunk routes and international links to Asia, the Middle East, New Zealand, and North America.",
    delayFactors: ["weather", "domestic peak waves", "international aircraft rotations"],
    popularSearches: ["Melbourne airport arrivals", "MEL departures today", "MEL airport live status", "Melbourne airport delays"],
    routeFocus: ["Sydney", "Singapore", "Dubai", "Auckland", "Los Angeles"],
  },
];

export function getAirportSeoProfile(code: string) {
  return airportSeoProfiles.find((airport) => airport.code === code.toUpperCase()) ?? null;
}
